### ISSUE TITLE
Multiple selection feature

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-list-box#10]
Several UX/DX tests participants would like to see multiple selection functionality in `vaadin-list-box`, so it will be possible to select multiple options by just adding `multiple` attribute to `vaadin-list-box`. (Selection process similar to native `select-option` multiple selection)

**Comment by jouni** [comment]
This has always been on the possible feature list and very likely needed. 

The problem is then how we handle the `selected` property (and the possible `value` property). Does `selected` return an array when the `multiple` property is set? Not sure how nice that kind of API is, that we couple properties tightly together.

**Comment by YuriyVaadin** [comment]
I think there is a way to do that. As `multiple` attribute in this case will introduce another way of selection functionality, we can introduce another property `multiple-selected` which will contain array of selected values. In the input part the items will be shown one by one with some delimiter (`,` `|` etc.)

**Comment by heruan** [comment]
Is this something we can expect out of beta? IIRC Grid also supports single/multi selection modes, List Box may handle this the same way.

**Comment by tomivirkki** [comment]
New features will need to wait for a minor release (after the stable is out). So this could be included in 1.1.0 earliest.

**Comment by oluwasayo** [comment]
Arrived here when looking for a Vaadin replacement for [Swing JList ListSelectionModel](https://docs.oracle.com/javase/8/docs/api/javax/swing/ListSelectionModel.html)

**Comment by robeden** [comment]
I could definitely see multi-selection making the (Flow, especially) API odd. Perhaps the best thing in that case would be "vaadin-multi-list-box" (or something) so the APIs wouldn't have to support both. In Vaadin 8, some of the APIs we quite strange from supporting both single and multiple selection.

But at the end of the day... the UI for this component with multiple selection is exactly what I want. 😄

**Comment by tamasnet** [comment]
+1

I realize this wasn't the philosophy `vaadin-list-box` was built on, but isn't single-selection just a special case of multi-selection?

**Comment by heruan** [comment]
Vaadin definitely lacks a multi-select component. The only way to achieve this is using the grid, which is an overkill for a simple multi-select and doesn't always fit. Related issues:

- https://github.com/vaadin/vaadin-combo-box/issues/88
- https://github.com/vaadin/vaadin-select/issues/160

**Comment by jouni** [comment]
> Vaadin definitely lacks a multi-select component.

Very much agreed. It’s more than sad IMO that one of the oldest issues for the whole component set is [”multi-select for combo box”](
https://github.com/vaadin/vaadin-combo-box/issues/88).

The current plan is to work on a multi-selection component next quarter. We figured we’d start with combo box, as it has been there for a long time and we’ve seen the community and customers build their own versions of it already, so it seems the most requested one.

If you think we should start with list-box instead, please let us know.

**Comment by robeden** [comment]
@jouni - I think there’s room for both, so I have no objection to combo boxes. The only argument I’d make for this one is it seems quite a bit simpler (from a UX and implementation perspective) so it might take less time to complete.

**Comment by heruan** [comment]
Correct me if I'm wrong, @jouni: `vaadin-list-box` is used by `vaadin-select`, so this and vaadin/vaadin-select#60 are basically the same issue?

Talking about priorities, I think that if multi selection isn't implementent in both component during a short time frame, users might choose the wrong component just beacuase it has the feature (and the other not yet).

Multi selection is more a crossing-cut concern than a single-component feature and I'd like to see a common pattern used among Vaadin components.

**Comment by jouni** [comment]
> but isn't single-selection a special case of multi-selection?

Yes, it is. Not sure why we did it like that with grid but then went the other way with list box.

Does anyone have opinions about the API? The suggestion in the description of using an additional `multiple` seems alright to me. Then the only trouble I see is in the `value` property, how that should be parsed into a valid selection (as it’s a string).

**Comment by yuriy-fix** [comment]
@jouni, we can follow the same logic as with [`selectedOptions`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/selectedOptions)  and have separate property for multi-selection.

**Comment by jouni** [comment]
> Correct me if I'm wrong, @jouni: `vaadin-list-box` is used by `vaadin-select`, so this and [vaadin/vaadin-select#160](https://github.com/vaadin/vaadin-select/issues/160) are basically the same issue?

Basically, yes.

> Multi selection is more a crossing-cut concern than a single-component feature and I'd like to see a common pattern used among Vaadin components.

Yes, that should be the target, that all components that manipulate some selection would have the same API.

> Talking about priorities, I think that if multi selection isn't implementent in both component during a short time frame, users might choose the wrong component just beacuase it has the feature (and the other not yet).

I understand the concern, but I’m not sure what we should do about that, except throw more developers at it 😄 Not sure if this is such a big concern that we can afford to put more hands implementing it for all the components at the same time.

> we can follow the same logic as with [`selectedOptions`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/selectedOptions) and have separate property for multi-selection.

Yeah, that looks good. That should align with Grid and Combo Box as well.

**Comment by samiheikki** [comment]
Created a prototype for multi selection based on the conversation at this ticket.
PR: https://github.com/vaadin/vaadin-list-mixin/pull/54

<img width="745" alt="Screenshot 2019-06-30 at 13 37 50" src="https://user-images.githubusercontent.com/8615573/60395444-476a4280-9b3c-11e9-9aea-fc125a79e9e0.png">
<img width="423" alt="Screenshot 2019-06-30 at 13 37 43" src="https://user-images.githubusercontent.com/8615573/60395445-476a4280-9b3c-11e9-8cfb-c3ba72b887b3.png">
