### ISSUE TITLE
Should we introduce dedicated label explicitly specified as attribute?

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-list-box#11]
Several UX/DX tests participants would like to have possibility to explicitly set `label` in `vaadin-list-box` like for example we are doing it in `vaadin-text-field`.

**Comment by jouni** [comment]
My suggestion is to not avoid this. Instead, move into the direction where we have the generic field features (label, error message, etc.) in a separate element (something like `<vaadin-custom-field>` currently), and separate input elements that can be used with it.

In addition, we can consider offering convenience field components, for example `<vaadin-list-box-field>`. For Flow/Java, those would probably even more helpful in reducing boilerplate code when creating forms.

**Comment by web-padawan** [comment]
> My suggestion is to avoid this

Then let me close this issue. I agree that `vaadin-custom-field` is a proper way to solve this.

Let's submit another issue (feature request) if we decide to have `vaadin-list-box-field`.
