### ISSUE TITLE
An example needed on using items property 

### ISSUE THREAD

**Issue by mikkoi-vaadin** [vaadin/vaadin-list-box#34]
Website feedback: "In the vaadin-list-box HTML please include an example using items property"

Please close this issue after this request is processed: https://github.com/vaadin/vaadin.com/issues/31

**Comment by jouni** [comment]
This component does not have a `items` property – you place `<vaadin-item>` elements inside the element directly.

Not exactly sure how to alleviate this confusion, which comes from `vaadin-combo-box` and `vaadin-grid` I suppose.

**Comment by web-padawan** [comment]
Should be addressed by vaadin/vaadin-list-mixin#38 and looks like we need
- 2.0.1 release for `vaadin-list-mixin`
- 1.0.3 release for `vaadin-list-box`

**Comment by web-padawan** [comment]
Both versions mentioned in the above comment are released with the updated documentation.
