### ISSUE TITLE
Incorrect initial rendering in Edge

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-list-box#38]
The items are rendered without the left padding. After you hover over the items the padding is applied.

![list-box-edge](https://user-images.githubusercontent.com/66382/42279239-d5fc77ba-7fa5-11e8-908d-4f5fe40cde61.gif)

Test case: http://output.jsbin.com/xekoyos (the right side list is a vaadin-list-box, on the left is a vaadin-grid)

**Comment by web-padawan** [comment]
Worked for me in Edge 17 but confirmed the issue in IE11, can be seen in https://polymer3-webpack-starter.herokuapp.com

**Comment by web-padawan** [comment]
Calling `updateStyles()` for the items makes it work:

```js
      let style;
      if (window.ShadyCSS) {
        style = ShadyCSS.getComputedStyleValue(this, '--_lumo-item-selected-icon-display');
      } else {
        style = getComputedStyle(this).getPropertyValue('--_lumo-item-selected-icon-display');
      }
      // console.log('display: ', style);
      this.items.forEach(item => {
        orientation ? item.setAttribute('orientation', orientation) : item.removeAttribute('orientation');
        item.updateStyles({'--_lumo-item-selected-icon-display': style});
      });
```

But of course we should not rely on any specific custom property names in the list-mixin (this is just a demo). Will investigate further about how to invoke `updateStyles()` properly.
