### ISSUE TITLE
UX/DX tests and fixes

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-list-box#4]
Plan, book, conduct and report.

**Comment by YuriyVaadin** [comment]
<b>UX Part</b> will be conducted with demo pages of the `vaadin-list-box`
<b>DX Part</b> https://gitlab.vaadin.com/elements/dx-tests/compare/master...wip%2Fvaadin-list-box%2Fv1.0.0-alpha2

**Comment by YuriyVaadin** [comment]
<b>Prepared combined document:</b> https://docs.google.com/document/d/1TnoPew1xZwwsvX9GwGelX98IByZ69J1ysLi9eVn6t4I/edit#heading=h.u1kv5zpv1526
