### ISSUE TITLE
Improve demos

### ISSUE THREAD

**Issue by shadikhani** [vaadin/vaadin-list-box#59]

**Comment by Haprog** [comment]
Reopening this as the PR got merged just before I was able to submit my review. Please fix the issues noted here: https://github.com/vaadin/vaadin-list-box/pull/62#pullrequestreview-311037424

**Comment by web-padawan** [comment]
Oops, sorry about that, I wasn't aware of you performing a review as well 😕

**Comment by Haprog** [comment]
Yeah I think GitHub UI has some room for improvement to show what's happening if someone else is currently writing a review. I should have probably assigned myself as a reviewer first and commented something that I started to review.

I did notice that you had added approval to the PR a bit before you merged but I didn't really have time to react to it and I didn't want to submit an incomplete review.

**Comment by Haprog** [comment]
Fixed by #62 and #63
