### ISSUE TITLE
Offer an api for getting the selected item

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-list-box#7]
e.g. vaadin-drop-down needs to access private API in order to get the selected item.

Additionally it would be nice to select an item by providing the item without having to know it's index in the dom.

Proposed API
```
   menu.selectedElement;
   menu.setSelected(itemElement);
```

**Comment by manolo** [comment]
An easier and simpler option is make `items` public so as it's developer responsibility to implements a way for visiting and selecting items

**Comment by web-padawan** [comment]
> An easier and simpler option is make items public 

This was changed long ago by vaadin/vaadin-list-mixin@4fb07b

Regarding `selectedItem`: we might want to have it in the next generation components.
So I'm closing this issue in favor of a newer one: vaadin/component-mixins#24
