### ISSUE TITLE
2.5.0 is missing _scrollToLastSelectedItem 

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-list-box#85]
The fix created for https://github.com/vaadin/vaadin-list-box/issues/74 is not available in the 2.5.0 release. It's private API, so it's technically not breaking, but this prevents the use of the workaround `_scrollToLastSelectedItem` was created for.

**Comment by web-padawan** [comment]
Released https://github.com/vaadin/vaadin-list-mixin/releases/tag/v2.5.1
