### ISSUE TITLE
MultiselectListBox looses its value after remove() and add()

### ISSUE THREAD

**Issue by wofl** [vaadin/vaadin-list-box#93]
**Version:**
Seen on vaadin 14.4.6 - high likelyhood this also is present in more recent versions (code not changed AFAIK)

**Description:**
The MultiselectListBox does not preserve its set value when the component is added to a container that already exists, removed and then added again. This most certainly is due to a `rebuild()` in an attach listener added to the ListBoxBase class that does also `clear()`. 

**Steps To Reproduce:**
```java
final List<String> listBoxItems = Arrays.asList("1", "2", "3", "4");
final MultiSelectListBox<String> listBox = new MultiSelectListBox<>();
listBox.setItems(listBoxItems);
listBox.setValue(Collections.singleton("2"));
final Button addButton = new Button("add");
add(addButton);
addButton.addClickListener(event -> {
    add(listBox);
    remove(listBox);
    add(listBox);
});
```

**Expected Result:**
The MultiselectListBox keeps its value no matter how many times and where it is added/removed.

**Comment by wofl** [comment]
Probably connected to #89

**Comment by mlindfors** [comment]
Can confirm, this is still happening with 14.5.1.

**Comment by wofl** [comment]
IMHO this commit is to blame:
https://github.com/vaadin/vaadin-list-box-flow/commit/1770c9cdb255634da1a9855e74c4c3e52e893dc4#diff-eaabd1720775821486e5442215444f3d640d8d2aa92e18652c89437fc85e7b77R70-R77
